### PR TITLE
[FEATURE] Hottest categories endpoint

### LINKED ISSUE #94: [FEATURE] Implement 'Hot Categories' endpoint

### PR DESCRIPTION
**Pull request by juanyepesp**
**CLOSING ISSUES:**
- closes #94

**DESCRIPTION:**
- This implements a new endpoint for getting the hottest categories, which means, the categories with most reviews on all spots. The `get_hottest_categories()` function will get all of the categories from all reviews, and count and sort them. This will enable for further development in both @ISIS3510-202410-Team23/flutter-team and @ISIS3510-202410-Team23/swift-team!!

- I assigned two people from each team for a review, if you want any changes made or any other inquiry, let me know!

**API Response:**

Screenshot 2024-05-12 at 6 33 10 PM

### CODE REVIEW

**Review by Laurarestrepo03 — COMMENTED** [review]
Question: how do you get the reviews from the latest week?

**Comment by juanyepesp** [comment]
> Question: how do you get the reviews from the latest week?

Ooh you're right I forgot we had defined this, let me change it up a little then

**Comment by juanyepesp** [comment]
@Laurarestrepo03 I just added the changes, please check again!!

**Comment by Laurarestrepo03** [comment]
This slay…

blushing emoji

**Comment by Laurarestrepo03** [comment]
> This slay…
> 
> blushing emoji

I forgot to approve hehe

**Review by Laurarestrepo03 — APPROVED** [review]

**Pull request merged**
